/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.11.1/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
  // Use sdkman instead for downloading SDK: JDK
  // Apply the foojay-resolver plugin to allow automatic download of JDKs
  //  latest release version listed at https://plugins.gradle.org/plugin/org.gradle.toolchains.foojay-resolver-convention
  // id("org.gradle.toolchains.foojay-resolver-convention") version "0.10.0"
  // alias(libs.plugins.foojay.resolver.convention)
}

rootProject.name = "ERDelta"
include("app")
