/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.11.1/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
  // ref for how to use version variable:
  //  https://docs.gradle.org/current/userguide/plugins.html
  val kotlin_version: String by settings

  plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    //  latest release version listed at https://plugins.gradle.org/plugin/org.gradle.toolchains.foojay-resolver-convention
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.10.0"

    // kotlin("jvm") version is same as kotlin_version
    // latest release version as per https://plugins.gradle.org/plugin/org.jetbrains.kotlin.plugin.serialization
    // which is same as `kotlin_version`; next statement 
    kotlin("plugin.serialization") version "$kotlin_version"
  }
}

rootProject.name = "FinTool"
include("app")
