/*
 * This file was generated by the Gradle 'init' task except the ktor parts
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.11.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
  // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
  // equivalent to
  //   kotlin("jvm") version libs.versions.kotlin.get()
  alias(libs.plugins.jvm)
  alias(libs.plugins.serialization)

  // Apply the application plugin to add support for building a CLI application in Java.
  application
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}

repositories {
  // Use Maven Central for resolving dependencies.
  mavenCentral()
}

dependencies {
  // This dependency is used by the application.
  implementation(libs.guava)
  implementation(libs.kotlinx.coroutines.core)
  implementation(libs.ktor.client.core)
  implementation(libs.ktor.client.cio)
  implementation(libs.ktor.client.content.negotiation)
  implementation(libs.ktor.serialization.kotlinx.json)
  implementation(libs.kotlinx.serialization.json)
}

testing {
  suites {
    // Configure the built-in test suite
    val test by getting(JvmTestSuite::class) {
      // Use Kotlin Test test framework
      useKotlinTest(libs.versions.kotlin.get())
    }
  }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(libs.versions.java.get().toInt())
  }
}

application {
  // Define the main class for the application.
  mainClass = "ERDelta.AppKt"
}
